# docker-compose.production.yml
version: '3'

volumes:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  backend:
    image: okojdan/regru_taski_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: okojdan/regru_taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: okojdan/regru_taski_gateway  # Качаем с Docker Hub
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80